// Code generated by MockGen. DO NOT EDIT.
// Source: send_verification_mail_inputport.go
//
// Generated by this command:
//
//	mockgen -source=send_verification_mail_inputport.go -destination=mock/send_verification_mail_inputport.go
//

// Package mock_inputport is a generated GoMock package.
package apiInputportMock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSendVerificationMailInputPort is a mock of SendVerificationMailInputPort interface.
type MockSendVerificationMailInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockSendVerificationMailInputPortMockRecorder
	isgomock struct{}
}

// MockSendVerificationMailInputPortMockRecorder is the mock recorder for MockSendVerificationMailInputPort.
type MockSendVerificationMailInputPortMockRecorder struct {
	mock *MockSendVerificationMailInputPort
}

// NewMockSendVerificationMailInputPort creates a new mock instance.
func NewMockSendVerificationMailInputPort(ctrl *gomock.Controller) *MockSendVerificationMailInputPort {
	mock := &MockSendVerificationMailInputPort{ctrl: ctrl}
	mock.recorder = &MockSendVerificationMailInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendVerificationMailInputPort) EXPECT() *MockSendVerificationMailInputPortMockRecorder {
	return m.recorder
}

// SendEmailWithVerificationCode mocks base method.
func (m *MockSendVerificationMailInputPort) SendEmailWithVerificationCode(email string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailWithVerificationCode", email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendEmailWithVerificationCode indicates an expected call of SendEmailWithVerificationCode.
func (mr *MockSendVerificationMailInputPortMockRecorder) SendEmailWithVerificationCode(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailWithVerificationCode", reflect.TypeOf((*MockSendVerificationMailInputPort)(nil).SendEmailWithVerificationCode), email)
}
