// Code generated by MockGen. DO NOT EDIT.
// Source: time_provider.go
//
// Generated by this command:
//
//	mockgen -source=time_provider.go -destination=mock/time_provider.go
//

// Package mock_util is a generated GoMock package.
package mock_util

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTimeProvider is a mock of TimeProvider interface.
type MockTimeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTimeProviderMockRecorder
	isgomock struct{}
}

// MockTimeProviderMockRecorder is the mock recorder for MockTimeProvider.
type MockTimeProviderMockRecorder struct {
	mock *MockTimeProvider
}

// NewMockTimeProvider creates a new mock instance.
func NewMockTimeProvider(ctrl *gomock.Controller) *MockTimeProvider {
	mock := &MockTimeProvider{ctrl: ctrl}
	mock.recorder = &MockTimeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeProvider) EXPECT() *MockTimeProviderMockRecorder {
	return m.recorder
}

// ExpiryTimeCalculator mocks base method.
func (m *MockTimeProvider) ExpiryTimeCalculator() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpiryTimeCalculator")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// ExpiryTimeCalculator indicates an expected call of ExpiryTimeCalculator.
func (mr *MockTimeProviderMockRecorder) ExpiryTimeCalculator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpiryTimeCalculator", reflect.TypeOf((*MockTimeProvider)(nil).ExpiryTimeCalculator))
}

// Now mocks base method.
func (m *MockTimeProvider) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimeProviderMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeProvider)(nil).Now))
}

// TodaysDate mocks base method.
func (m *MockTimeProvider) TodaysDate() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TodaysDate")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// TodaysDate indicates an expected call of TodaysDate.
func (mr *MockTimeProviderMockRecorder) TodaysDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TodaysDate", reflect.TypeOf((*MockTimeProvider)(nil).TodaysDate))
}
