// Code generated by MockGen. DO NOT EDIT.
// Source: uuid_generator.go
//
// Generated by this command:
//
//	mockgen -source=uuid_generator.go -destination=mock/uuid_generator.go
//

// Package mock_util is a generated GoMock package.
package mock_util

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUUIDGenerator is a mock of UUIDGenerator interface.
type MockUUIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDGeneratorMockRecorder
	isgomock struct{}
}

// MockUUIDGeneratorMockRecorder is the mock recorder for MockUUIDGenerator.
type MockUUIDGeneratorMockRecorder struct {
	mock *MockUUIDGenerator
}

// NewMockUUIDGenerator creates a new mock instance.
func NewMockUUIDGenerator(ctrl *gomock.Controller) *MockUUIDGenerator {
	mock := &MockUUIDGenerator{ctrl: ctrl}
	mock.recorder = &MockUUIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUIDGenerator) EXPECT() *MockUUIDGeneratorMockRecorder {
	return m.recorder
}

// NewV7 mocks base method.
func (m *MockUUIDGenerator) NewV7() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewV7")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewV7 indicates an expected call of NewV7.
func (mr *MockUUIDGeneratorMockRecorder) NewV7() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewV7", reflect.TypeOf((*MockUUIDGenerator)(nil).NewV7))
}
