// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interactor/inputport/auth_interactor_inputport.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/interactor/inputport/auth_interactor_inputport.go -destination=internal/domain/interactor/inputport/mock/auth_interactor_inputport.go
//

// Package mock_inputport is a generated GoMock package.
package mock_inputport

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthInteractorInputPort is a mock of AuthInteractorInputPort interface.
type MockAuthInteractorInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthInteractorInputPortMockRecorder
	isgomock struct{}
}

// MockAuthInteractorInputPortMockRecorder is the mock recorder for MockAuthInteractorInputPort.
type MockAuthInteractorInputPortMockRecorder struct {
	mock *MockAuthInteractorInputPort
}

// NewMockAuthInteractorInputPort creates a new mock instance.
func NewMockAuthInteractorInputPort(ctrl *gomock.Controller) *MockAuthInteractorInputPort {
	mock := &MockAuthInteractorInputPort{ctrl: ctrl}
	mock.recorder = &MockAuthInteractorInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthInteractorInputPort) EXPECT() *MockAuthInteractorInputPortMockRecorder {
	return m.recorder
}

// SignUp mocks base method.
func (m *MockAuthInteractorInputPort) SignUp(ctx context.Context, signupParams entities.SignUp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, signupParams)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockAuthInteractorInputPortMockRecorder) SignUp(ctx, signupParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockAuthInteractorInputPort)(nil).SignUp), ctx, signupParams)
}
