// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/inputport/auth_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/inputport/auth_repository_inputport.go -destination=internal/domain/repository/inputport/mock/auth_repository_inputport.go
//

// Package mock_inputport is a generated GoMock package.
package mock_inputport

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepositoryInputPort is a mock of AuthRepositoryInputPort interface.
type MockAuthRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryInputPortMockRecorder is the mock recorder for MockAuthRepositoryInputPort.
type MockAuthRepositoryInputPortMockRecorder struct {
	mock *MockAuthRepositoryInputPort
}

// NewMockAuthRepositoryInputPort creates a new mock instance.
func NewMockAuthRepositoryInputPort(ctrl *gomock.Controller) *MockAuthRepositoryInputPort {
	mock := &MockAuthRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepositoryInputPort) EXPECT() *MockAuthRepositoryInputPortMockRecorder {
	return m.recorder
}

// InsertVerificationCode mocks base method.
func (m *MockAuthRepositoryInputPort) InsertVerificationCode(ctx context.Context, verificationCode entities.VerificationCodes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVerificationCode", ctx, verificationCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVerificationCode indicates an expected call of InsertVerificationCode.
func (mr *MockAuthRepositoryInputPortMockRecorder) InsertVerificationCode(ctx, verificationCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVerificationCode", reflect.TypeOf((*MockAuthRepositoryInputPort)(nil).InsertVerificationCode), ctx, verificationCode)
}
