// Code generated by MockGen. DO NOT EDIT.
// Source: user_repository_inputport.go
//
// Generated by this command:
//
//	mockgen -source=user_repository_inputport.go -destination=mock/user_repository_inputport.go
//

// Package mock_inputport is a generated GoMock package.
package mock_inputport

import (
	entities "backend/internal/domain/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepositoryInputPort is a mock of UserRepositoryInputPort interface.
type MockUserRepositoryInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInputPortMockRecorder
	isgomock struct{}
}

// MockUserRepositoryInputPortMockRecorder is the mock recorder for MockUserRepositoryInputPort.
type MockUserRepositoryInputPortMockRecorder struct {
	mock *MockUserRepositoryInputPort
}

// NewMockUserRepositoryInputPort creates a new mock instance.
func NewMockUserRepositoryInputPort(ctrl *gomock.Controller) *MockUserRepositoryInputPort {
	mock := &MockUserRepositoryInputPort{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInputPort) EXPECT() *MockUserRepositoryInputPortMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepositoryInputPort) CreateUser(ctx context.Context, user entities.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryInputPortMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepositoryInputPort)(nil).CreateUser), ctx, user)
}

// FindUserByEmail mocks base method.
func (m *MockUserRepositoryInputPort) FindUserByEmail(ctx context.Context, email string) (entities.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(entities.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockUserRepositoryInputPortMockRecorder) FindUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockUserRepositoryInputPort)(nil).FindUserByEmail), ctx, email)
}
